apiVersion: batch/v1
kind: CronJob
metadata:
  name: social-media-post
spec:
  # Runs at 00:00, 06:00, 09:00, 12:00, 16:00 every day (5 times per day)
  schedule: "0 0,6,9,12,16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: social-media-pro
            image: <your-docker-image:tag>
            envFrom:
            - secretRef:
                name: social-media-env  # Store your .env as a Kubernetes Secret
          restartPolicy: OnFailure
